### ISSUE TITLE
unhandled exception polling TrustedAdvisor

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#155]
This appears to have just started in the last 24 hours. While polling Trusted Advisor with awslimitchecker 0.3.1:

```
INFO:botocore.credentials:Found credentials in environment variables.
INFO:awslimitchecker.connectable:Connected to support in region us-east-1
INFO:awslimitchecker.trustedadvisor:Beginning TrustedAdvisor poll
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): support.us-east-1.amazonaws.com
Traceback (most recent call last):
  File "/home/jantman/GIT/awslimitchecker/docs/build_generated_docs.py", line 309, in <module>
    build_docs()
  File "/home/jantman/GIT/awslimitchecker/docs/build_generated_docs.py", line 305, in build_docs
    build_limits(c)
  File "/home/jantman/GIT/awslimitchecker/docs/build_generated_docs.py", line 100, in build_limits
    limits = checker.get_limits()
  File "/home/jantman/GIT/awslimitchecker/docs/../awslimitchecker/checker.py", line 179, in get_limits
    self.ta.update_limits()
  File "/home/jantman/GIT/awslimitchecker/docs/../awslimitchecker/trustedadvisor.py", line 113, in update_limits
    ta_results = self._poll()
  File "/home/jantman/GIT/awslimitchecker/docs/../awslimitchecker/trustedadvisor.py", line 152, in _poll
    if check['region'] != region:
KeyError: 'region'
```

or

```
INFO:botocore.credentials:Found credentials in environment variables.
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): support.us-east-1.amazonaws.com
Checking AWS resource usage; WARNING threshold 80% of limit, CRITICAL threshold 99% of limit
Traceback (most recent call last):
  File "./check_aws_limits.py", line 289, in <module>
    checker.run(error_on_warning=args.error_on_warning, verbose=args.verbose)
  File "./check_aws_limits.py", line 249, in run
    warnings, criticals = self.run_for_regions(regions, verbose=verbose)
  File "./check_aws_limits.py", line 230, in run_for_regions
    w, c = self.run_for_region(region=region, verbose=verbose)
  File "./check_aws_limits.py", line 201, in run_for_region
    return self.check_limits(region, verbose=verbose)
  File "./check_aws_limits.py", line 141, in check_limits
    checker.check_thresholds()
  File "/home/ec2-user/jenkins/workspace/ReleaseEngineering/awslimitchecker/awslimitchecker_dev/lib/python2.7/site-packages/awslimitchecker/checker.py", line 413, in check_thresholds
    self.ta.update_limits()
  File "/home/ec2-user/jenkins/workspace/ReleaseEngineering/awslimitchecker/awslimitchecker_dev/lib/python2.7/site-packages/awslimitchecker/trustedadvisor.py", line 113, in update_limits
    ta_results = self._poll()
  File "/home/ec2-user/jenkins/workspace/ReleaseEngineering/awslimitchecker/awslimitchecker_dev/lib/python2.7/site-packages/awslimitchecker/trustedadvisor.py", line 152, in _poll
    if check['region'] != region:
KeyError: 'region'
```

The problem is [here](https://github.com/jantman/awslimitchecker/blob/0.3.1/awslimitchecker/trustedadvisor.py#L152); it seems that the TA [DescribeTrustedAdvisorCheckResult](https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeTrustedAdvisorCheckResult.html) API action is now returning checks without a region, even though the API docs for the [TrustedAdvisorResourceDetail](https://docs.aws.amazon.com/awssupport/latest/APIReference/API_TrustedAdvisorResourceDetail.html) type still show ``region`` as a required element.

I can't find any recent release notes for Support or Trusted Advisor...

**Comment by jantman** [comment]
It appears that sometime in the past few days (specifically, between  Thu, 10 Mar 2016 07:00:00 GMT and  Fri, 11 Mar 2016 07:00:00 GMT for the account I'm testing with) Trusted Advisor rolled out five new checks for IAM-related things. These checks lack the ``region`` dictionary key that is marked as Required in the [TrustedAdvisorResourceDetail(https://docs.aws.amazon.com/awssupport/latest/APIReference/API_TrustedAdvisorResourceDetail.html) API documentation.

Example of these checks:

```
{'status': 'ok', 'resourceId': 'x', 'isSuppressed': False, 'metadata': ['-', 'IAM', 'Instance profiles', '500', '394', 'Green']}
{'status': 'ok', 'resourceId': 'x', 'isSuppressed': False, 'metadata': ['-', 'IAM', 'Roles', '500', '375', 'Green']}
{'status': 'ok', 'resourceId': 'x', 'isSuppressed': False, 'metadata': ['-', 'IAM', 'Groups', '100', '25', 'Green']}
{'status': 'ok', 'resourceId': 'x', 'isSuppressed': False, 'metadata': ['-', 'IAM', 'Users', '5000', '152', 'Green']}
{'status': 'ok', 'resourceId': 'x', 'isSuppressed': False, 'metadata': ['-', 'IAM', 'Server certificates', '100', '55', 'Green']}
```

**Comment by jmetzmeier** [comment]
:+1: thanks for the fix

**Comment by jantman** [comment]
Any time :)

I put in a rather strongly-worded support request on $EMPLOYER's largest AWS account, inquiring about both violating the published API, and not announcing or documenting the change...
