### ISSUE TITLE
set_limit_override() takes at least 4 arguments (2 given)

### ISSUE THREAD

**Issue by akabdog** [jantman/awslimitchecker#174]
### Version
awslimitchecker 0.4.1

### Installation Method
pip install awslimitchecker
no virtualenv being used

### Supporting Software Versions
Python 2.7.10
ubuntu server 15.10

### Actual Output
I'm probably doing this wrong, but here is my code:
```
#!/usr/bin/env python
import logging
logging.basicConfig()
logger = logging.getLogger()
from awslimitchecker.checker import AwsLimitChecker
regions = ['us-east-1','us-west-1','eu-central-1','ap-southeast-1']
limits = {
        'us-east-1': {'EC2': {'VPC security groups per elastic network interface': 10}},
        'us-east-1': {'EBS': {'Provisioned IOPS (SSD) storage (GiB)': 500000}},
        'us-west-1': {'EBS': {'Provisioned IOPS (SSD) storage (GiB)': 500000}},
}
for r in regions:
        c = AwsLimitChecker(region=r)
        print "###################### " + r + " ########################"
        for k, v in limits.iteritems():
                if r == k :
                        print "adding custom limit for this region:", v
                        c.set_limit_override(v)
```

output from running the code:
```
adding custom limit for this region: {'EC2': {'VPC security groups per elastic network interface': 10}}
Traceback (most recent call last):
  File "./awslimitchecker-tenable.py", line 35, in <module>
    c.set_limit_override(v)
TypeError: set_limit_override() takes at least 4 arguments (2 given)
```

### Expected Output
no error

### Testing Assistance

sure and thanks for the help!

**Comment by akabdog** [comment]
I also tried:
```
c.set_limit_override(**v)
```
And saw this error:
```
TypeError: set_limit_override() got an unexpected keyword argument 'EC2'
```

**Comment by jantman** [comment]
@akabdog this should be pretty easy to fix... [AwsLimitChecker.set_limit_override()](https://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.set_limit_override) takes three arguments: the service name, the limit name, and the value.

My recommendation would be something like (untested):

```python
for r in regions:
        c = AwsLimitChecker(region=r)
        print "###################### " + r + " ########################"
        if r in limits:
                for svc_name, svc_overrides in limits[r].iteritems():
                        for lim_name, lim_val in svc_overrides.iteritems():
                            print("Setting %s:%s limit override to %s" % (svc_name, lim_name, lim_val))
                            c.set_limit_override(svc_name, lim_name, lim_val)
```

**Comment by akabdog** [comment]
Thanks so much, that gets me really close to working. I had to switch my data structure a bit but I think it's almost working.
Here is the error I'm getting:
```
Setting us-east-1:EC2 limit override to {'VPC security groups per elastic network interface': 10}
Traceback (most recent call last):
  File "./awslimitchecker-tenable.py", line 34, in <module>
    c.set_limit_override(svc_name, lim_name, lim_val)
  File "/home/bsmith01/.local/lib/python2.7/site-packages/awslimitchecker/checker.py", line 289, in set_limit_override
    self.services[service_name].set_limit_override(
KeyError: 'us-east-1'
```
my code:
```
regions = ['us-east-1','us-west-1','eu-central-1','ap-southeast-1']
limits = []
limits.append({'us-east-1': {'EC2': {'VPC security groups per elastic network interface': 10}}})
limits.append({'us-east-1': {'EBS': {'Provisioned IOPS (SSD) storage (GiB)': 500000}}})
limits.append({'us-east-1': {'EBS': {'General Purpose (SSD) volume storage (GiB)': 100000}}})
limits.append({'us-west-1': {'EBS': {'General Purpose (SSD) volume storage (GiB)': 100000}}})

for region in regions:
        c = AwsLimitChecker(region=region)
        print "###################### " + region + " ########################"
        for limit in limits:
                if region in limit:
                        for svc_name, svc_overrides in limit.iteritems():
                                for lim_name, lim_val in svc_overrides.iteritems():
                                        print("Setting %s:%s limit override to %s" % (svc_name, lim_name, lim_val))
                                        c.set_limit_override(svc_name, lim_name, lim_val)
```

**Comment by jantman** [comment]
Sorry... I probably should've reproduced the complete snippet in my last response, to save you some time and frustration. Apologies.

Assuming I'm understanding your code and desired outcome correctly, this would be my suggestion:

```python
regions = ['us-east-1','us-west-1','eu-central-1','ap-southeast-1']
limits = {
    'us-east-1': {
        'EC2': {
            'VPC security groups per elastic network interface': 10
        },
        'EBS': {
            'Provisioned IOPS (SSD) storage (GiB)': 500000,
            'General Purpose (SSD) volume storage (GiB)': 100000
        }
    },
    'us-west-1': {
        'EBS': {
            'General Purpose (SSD) volume storage (GiB)': 100000
        }
    }

for r in regions:
        c = AwsLimitChecker(region=r)
        print "###################### " + r + " ########################"
        if r in limits:
                for svc_name, svc_overrides in limits[r].iteritems():
                        for lim_name, lim_val in svc_overrides.iteritems():
                            print("Setting %s:%s limit override to %s" % (svc_name, lim_name, lim_val))
                            c.set_limit_override(svc_name, lim_name, lim_val)
```

As far as I can tell (I only eyeballed it, I didn't carefully compare or diff the snippets) the only difference is the ``limits`` variable. In your latest snippet, you're making it a list and appending dicts to it, but the example I wrote was expecting a nested dict.

I also used a dictionary literal for the ``limits`` variable; it's considered more Pythonic and the recommended style when building a dict that's populated all at once in the source with literals, as opposed to programmatically built.

The example above is very similar to how I'm doing it for my current employer, though we store the overrides in per-region JSON files and then load them in, so that updating the overrides doesn't require touching an actual source file.

**Comment by akabdog** [comment]
That works great, totally above and beyond supporting this code, thanks so much!

**Comment by jantman** [comment]
Great to hear! I know what it's like to find something that seems like it could help and just want to get it working, so I try my best as time allows.

I'm going to close this issue, but if you run into any other problems feel free to reopen it, I'll assist as best I can.
