### ISSUE TITLE
versionfinder requires git to be installed

### ISSUE THREAD

**Issue by sstarcher** [jantman/awslimitchecker#282]
### Version

0.9.0

### Installation Method

docker container with from python:2.7-slim and pip for awslimitchecker 0.9.0

### Supporting Software Versions

The output of ``python --version`` and ``virtualenv --version`` in the environment
that awslimitchecker is running in, as well as your operating system type and version.

### Actual Output

```
root@442148ccb802:/# awslimitchecker -vv
Traceback (most recent call last):
  File "/usr/local/bin/awslimitchecker", line 7, in <module>
    from awslimitchecker.runner import console_entry_point
  File "/usr/local/lib/python2.7/site-packages/awslimitchecker/runner.py", line 46, in <module>
    from .checker import AwsLimitChecker
  File "/usr/local/lib/python2.7/site-packages/awslimitchecker/checker.py", line 43, in <module>
    from .version import _get_version_info
  File "/usr/local/lib/python2.7/site-packages/awslimitchecker/version.py", line 46, in <module>
    from versionfinder import find_version
  File "/usr/local/lib/python2.7/site-packages/versionfinder/__init__.py", line 39, in <module>
    from .versionfinder import VersionFinder
  File "/usr/local/lib/python2.7/site-packages/versionfinder/versionfinder.py", line 60, in <module>
    from git import Repo
  File "/usr/local/lib/python2.7/site-packages/git/__init__.py", line 45, in <module>
    from git.repo import Repo               # @NoMove @IgnorePep8
  File "/usr/local/lib/python2.7/site-packages/git/repo/__init__.py", line 4, in <module>
    from .base import *
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 31, in <module>
    from git.remote import Remote, add_progress, to_progress_instance
  File "/usr/local/lib/python2.7/site-packages/git/remote.py", line 190, in <module>
    class FetchInfo(object):
  File "/usr/local/lib/python2.7/site-packages/git/remote.py", line 219, in FetchInfo
    v = Git().version_info[:2]
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 461, in version_info
    return self._version_info
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 424, in __getattr__
    return LazyMixin.__getattr__(self, name)
  File "/usr/local/lib/python2.7/site-packages/gitdb/util.py", line 256, in __getattr__
    self._set_cache_(attr)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 444, in _set_cache_
    version_numbers = self._call_process('version').split(' ')[2]
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 877, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 602, in execute
    raise GitCommandNotFound(command, err)
git.exc.GitCommandNotFound: Cmd('git') not found due to: OSError('[Errno 2] No such file or directory')
  cmdline: git version
```

### Expected Output
no stack trace

### Testing Assistance

sure

**Comment by jantman** [comment]
Yeah, that's a bug. Sorry. It's a bit troubling it's been in the wild for this long without anyone reporting it.

It's probably going to be a few days before I can get a new release out, but I'll do my best...

**Comment by sstarcher** [comment]
No problem, I was running 0.7.0 until today.  I dropped git into my docker container for now.

Thanks for the quick response.

**Comment by jantman** [comment]
Sure. Sorry about that!

**Comment by jantman** [comment]
@sstarcher [versionfinder 0.1.1](https://pypi.python.org/pypi/versionfinder/0.1.1) is out on PyPI and should fix this. Apologies for the inconvenience.

**Comment by jantman** [comment]
... and apologies for closing this prematurely. awslimitchecker has versionfinder pinned to 0.1.0, so I'll need to cut a new release to bump that and pull in the changes.

**Comment by jantman** [comment]
@sstarcher awslimitchecker 0.10.0 was released 9 hours ago, and bumps versionfinder to ``>= 0.1.1``, which includes a fix for that bug. Thanks for taking the time to open this issue, and apologies for the problems.
