### ISSUE TITLE
Error checking services in specific regions

### ISSUE THREAD

**Issue by agassner** [jantman/awslimitchecker#336]
I'm getting an error when checking a specific region **sa-east-1** (Sao Paulo)
It seems that it checks for all services and when it gets to EFS, a timeout error is thrown.
Bear in mind that **sa-east-1** does not have EFS service.

Does the checker checks for all services in a region even though the region does not have all of them available?

**Comment by jantman** [comment]
@agassner Can you please paste the fields that were requested in the [template that should have been pre-populated when you opened this issue](https://github.com/jantman/awslimitchecker/blob/master/.github/ISSUE_TEMPLATE.md), at least the specific version of awslimitchecker and the debug-level output showing the error message?

I think this may be related to #335 but I can't be sure without seeing the actual error.

Yes, this normally checks all services in a region even though the region doesn't have all of them available. It seems that something has changed with EFS in the past week or so which could be causing this...

**Comment by agassner** [comment]
@jantman Thanks, it was more like a question than a bug report.

I'm adding more info just in case.

### Version

```
$ awslimitchecker --version
awslimitchecker 4.0.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
awslimitchecker 4.0.0 (see <https://github.com/jantman/awslimitchecker> for source code)
```

### Installation Method

Using pyenv.
`pip install awslimitchecker`

### Supporting Software Versions

```
$ python --version
Python 3.6.4

$ pyenv --version
pyenv 1.2.1

OS: Darwin Kernel Version 15.6.0: Tue Jan  9 20:12:05 PST 2018; root:xnu-3248.73.5~1/RELEASE_X86_64 x86_64
```

### Code

```
import logging

from awslimitchecker.checker import AwsLimitChecker


FORMAT = '%(message)s'
logging.basicConfig(format=FORMAT)
logger = logging.getLogger('wrapper')
logger.setLevel(logging.INFO)


c = AwsLimitChecker(
    account_id='111111111111',
    account_role='myrole',
    region='sa-east-1'
)

result = c.check_thresholds()
```

### Actual Output

```
$ python test.py
awslimitchecker 4.0.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
Traceback (most recent call last):
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 139, in _new_conn
    (self.host, self.timeout))
botocore.vendored.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPSConnection object at 0x107a56b38>, 'Connection to elasticfilesystem.sa-east-1.amazonaws.com timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
botocore.vendored.requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='elasticfilesystem.sa-east-1.amazonaws.com', port=443): Max retries exceeded with url: /2015-02-01/file-systems (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x107a56b38>, 'Connection to elasticfilesystem.sa-east-1.amazonaws.com timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    result = c.check_thresholds()
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/awslimitchecker/checker.py", line 554, in check_thresholds
    tmp = cls.check_thresholds()
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/awslimitchecker/services/base.py", line 272, in check_thresholds
    self.find_usage()
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/awslimitchecker/services/efs.py", line 67, in find_usage
    self._find_usage_filesystems()
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/awslimitchecker/services/efs.py", line 82, in _find_usage_filesystems
    alc_marker_param='Marker'
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/awslimitchecker/utils.py", line 146, in paginate_dict
    result = function_ref(*argv, **pass_kwargs)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/endpoint.py", line 213, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/agassner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
botocore.vendored.requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='elasticfilesystem.sa-east-1.amazonaws.com', port=443): Max retries exceeded with url: /2015-02-01/file-systems (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x107a56b38>, 'Connection to elasticfilesystem.sa-east-1.amazonaws.com timed out. (connect timeout=60)'))
```

**Comment by jantman** [comment]
@agassner thank you for the information.

I'm pretty sure this is the same thing I saw in #335 - something is changing with the EFS service lately. In #335, EFS in us-west-2 (where it's not supported) used to fail with a ``EndpointConnectionError`` (that awslimitchecker handles) but is now failing with an ``AccessDeniedException``. EFS is [not supported](https://docs.aws.amazon.com/general/latest/gr/rande.html#elasticfilesystem-region) in sa-east-1 either, and it seems that what happens when we try to connect has changed (but, strangely, is different from the new behavior in us-west-2).

I have a ticket open with AWS for this through my employer's Enterprise account, since we're also affected by it, but I haven't heard anything back yet. I'll ping them back today about it...

We came up with a temporary workaround for our purposes, where we just don't check EFS in regions that don't support it (until AWS fixes this).

To modify the example code you gave above to do the same thing:

```python
c = AwsLimitChecker(
    account_id='111111111111',
    account_role='myrole',
    region='sa-east-1'
)

services = [s for s in sorted(c.get_service_names()) if s != 'EFS']
result = c.check_thresholds(service=services)
```

We just call ``AwsLimitChecker.get_service_names()`` and then pass all service names but EFS as a list to the ``service=`` parameter of ``check_thresholds()``.

Do you mind if I close this issue as a duplicate of #335 and change the description of that to be more general, about handling the new issues when connecting to EFS?

**Comment by agassner** [comment]
@jantman Many thanks! That's very helpful.
Feel free to close this one and change the description.

**Comment by jantman** [comment]
Merging into #335.
