### ISSUE TITLE
Inaccurate number of ec2 instance types, and its available amount

### ISSUE THREAD

**Issue by Michael1001** [jantman/awslimitchecker#348]
Hi! 
Using the command:
awslimitchecker -l --region us-west-1
I get a result, that not corresponds to reality.
For example, on the aws web site, on the Limits, page, I've counted 79 ec2 available instance types, while the awslimitchecker, returns 100. Here is the types that does not exists on my account.
cc2.8xlarge
cg1.4xlarge
cr1.8xlarge
f1.16xlarge
f1.2xlarge
h1.16xlarge
h1.2xlarge
h1.4xlarge
h1.8xlarge
hi1.4xlarge
hs1.8xlarge
p2.16xlarge
p2.8xlarge
p2.xlarge
p3.16xlarge
p3.2xlarge
p3.8xlarge
x1.16xlarge
x1.32xlarge
x1e.32xlarge
x1e.xlarge

And information itself about amount of available instances, doesn't correspond to reality!
For example, having in reality:
Running On-Demand c1.medium instances == 100
, the command line tool, gives me 20. And so on. I've counted and more then 50% of information about available amount of ec2 instance types, are not correct.

**Comment by Michael1001** [comment]
**Version:**
`awslimitchecker --version`

awslimitchecker 4.0.2 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
Traceback (most recent call last):
  File "/home/ubuntu/limitchecker/bin/awslimitchecker", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/awslimitchecker/runner.py", line 409, in console_entry_point
    r.console_entry_point()
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/awslimitchecker/runner.py", line 366, in console_entry_point
    check_version=args.check_version
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/awslimitchecker/checker.py", line 170, in __init__
    boto_conn_kwargs)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/awslimitchecker/services/base.py", line 106, in __init__
    self.limits = self.get_limits()
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/awslimitchecker/services/dynamodb.py", line 142, in get_limits
    self.connect()
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/awslimitchecker/connectable.py", line 88, in connect
    self.conn = boto3.client(self.api_name, **kwargs)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/client.py", line 358, in resolve
    service_name, region_name)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Installation Method:**
`sudo apt install virtualenv`
`virtualenv limitchecker`
`source limitchecker/bin/activate`
`pip install awslimitchecker`


**Supporting Software Versions:**
`python -V`
Python 2.7.12

`virtualenv --version`
15.0.1

`lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial


**Actual Output**
`ubuntu@ip-172-31-0-227:~$ awslimitchecker -l --region us-west-1 -vv`
awslimitchecker 4.0.2 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
2018-06-16 12:24:06,513 [DEBUG utils.py:241 - awslimitchecker.utils._get_latest_version() ] Error getting latest version from PyPI
Traceback (most recent call last):
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/awslimitchecker/utils.py", line 234, in _get_latest_version
    j = r.json()
  File "/home/ubuntu/limitchecker/local/lib/python2.7/site-packages/botocore/vendored/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2018-06-16 12:24:06,514 [DEBUG checker.py:213 - awslimitchecker.checker._boto_conn_kwargs() ] Connecting to region us-west-1
2018-06-16 12:24:06,570 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to dynamodb in region us-west-1
2018-06-16 12:24:06,579 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to support in region us-east-1
2018-06-16 12:24:06,579 [INFO trustedadvisor.py:162 - awslimitchecker.trustedadvisor._poll() ] Beginning TrustedAdvisor poll
2018-06-16 12:24:06,579 [DEBUG trustedadvisor.py:219 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Querying Trusted Advisor checks
2018-06-16 12:24:06,958 [WARNING trustedadvisor.py:228 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
2018-06-16 12:24:06,958 [INFO trustedadvisor.py:165 - awslimitchecker.trustedadvisor._poll() ] TrustedAdvisor.have_ta is False; not polling TA
2018-06-16 12:24:06,958 [DEBUG trustedadvisor.py:402 - awslimitchecker.trustedadvisor._update_services() ] Updating TA limits on all services
2018-06-16 12:24:06,958 [INFO trustedadvisor.py:422 - awslimitchecker.trustedadvisor._update_services() ] Done updating TA limits on all services
2018-06-16 12:24:07,007 [INFO connectable.py:108 - awslimitchecker.connectable.connect_resource() ] Connected to iam (resource) in region aws-global
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccessKeysPerUserQuota
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountAccessKeysPresent
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountMFAEnabled
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountSigningCertificatesPresent
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AssumeRolePolicySizeQuota
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerGroupQuota
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerRoleQuota
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerUserQuota
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupPolicySizeQuota
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupsPerUserQuota
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevices
2018-06-16 12:24:07,514 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevicesInUse
2018-06-16 12:24:07,515 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: PolicySizeQuota
2018-06-16 12:24:07,515 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: Providers
2018-06-16 12:24:07,515 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: RolePolicySizeQuota
2018-06-16 12:24:07,515 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: SigningCertificatesPerUserQuota
2018-06-16 12:24:07,515 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: UserPolicySizeQuota
2018-06-16 12:24:07,515 [DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: VersionsPerPolicyQuota
2018-06-16 12:24:07,532 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to autoscaling in region us-west-1
2018-06-16 12:24:07,532 [INFO autoscaling.py:145 - awslimitchecker.services.autoscaling._update_limits_from_api() ] Querying EC2 DescribeAccountAttributes for limits
2018-06-16 12:24:07,606 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to ses in region us-west-1
2018-06-16 12:24:18,157 [WARNING ses.py:107 - awslimitchecker.services.ses._update_limits_from_api() ] Skipping SES: Could not connect to the endpoint URL: "https://email.us-west-1.amazonaws.com/"
2018-06-16 12:24:18,196 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to rds in region us-west-1
2018-06-16 12:24:18,197 [INFO rds.py:282 - awslimitchecker.services.rds._update_limits_from_api() ] Querying RDS DescribeAccountAttributes for limits
2018-06-16 12:24:18,282 [INFO rds.py:288 - awslimitchecker.services.rds._update_limits_from_api() ] RDS DescribeAccountAttributes returned unknownlimit: DBClusterRoles (max: 5; used: 0)
2018-06-16 12:24:18,282 [DEBUG rds.py:294 - awslimitchecker.services.rds._update_limits_from_api() ] Done setting limits from API.
2018-06-16 12:24:18,295 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to elb in region us-west-1
2018-06-16 12:24:18,295 [DEBUG elb.py:261 - awslimitchecker.services.elb._update_limits_from_api() ] Querying ELB DescribeAccountLimits for limits
2018-06-16 12:24:18,390 [DEBUG elb.py:277 - awslimitchecker.services.elb._update_limits_from_api() ] Connected to elbv2 in region us-west-1
2018-06-16 12:24:18,390 [DEBUG elb.py:278 - awslimitchecker.services.elb._update_limits_from_api() ] Querying ELBv2 (ALB) DescribeAccountLimits for limits
2018-06-16 12:24:18,491 [DEBUG elb.py:294 - awslimitchecker.services.elb._update_limits_from_api() ] Done setting limits from API
2018-06-16 12:24:18,491 [DEBUG directoryservice.py:125 - awslimitchecker.services.directoryservice._update_limits_from_api() ] Setting DirectoryService limits from API
2018-06-16 12:24:18,507 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to ds in region us-west-1
2018-06-16 12:24:18,671 [DEBUG cloudformation.py:107 - awslimitchecker.services.cloudformation._update_limits_from_api() ] Setting CloudFormation limits from API
2018-06-16 12:24:18,689 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to cloudformation in region us-west-1
2018-06-16 12:24:18,756 [DEBUG cloudformation.py:115 - awslimitchecker.services.cloudformation._update_limits_from_api() ] API response contained unknown CloudFormation limit: StackOutputsLimit
2018-06-16 12:24:18,756 [INFO dynamodb.py:219 - awslimitchecker.services.dynamodb._update_limits_from_api() ] Querying DynamoDB DescribeLimits for limits
2018-06-16 12:24:18,779 [DEBUG dynamodb.py:234 - awslimitchecker.services.dynamodb._update_limits_from_api() ] Done setting limits from API
2018-06-16 12:24:18,870 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to ec2 in region us-west-1
2018-06-16 12:24:18,891 [INFO connectable.py:108 - awslimitchecker.connectable.connect_resource() ] Connected to ec2 (resource) in region us-west-1
2018-06-16 12:24:18,891 [INFO ec2.py:285 - awslimitchecker.services.ec2._update_limits_from_api() ] Querying EC2 DescribeAccountAttributes for limits
2018-06-16 12:24:18,986 [DEBUG ec2.py:304 - awslimitchecker.services.ec2._update_limits_from_api() ] Done setting limits from API
ApiGateway/API keys per account                        500
ApiGateway/APIs per account                            60
ApiGateway/Client certificates per account             60
ApiGateway/Custom authorizers per API                  10
ApiGateway/Documentation parts per API                 2000
ApiGateway/Resources per API                           300
ApiGateway/Stages per API                              10
ApiGateway/Usage plans per account                     300
AutoScaling/Auto Scaling groups                        200 (API)
AutoScaling/Launch configurations                      200 (API)
CloudFormation/Stacks                                  200 (API)
Directory Service/CloudOnlyDirectories                 10 (API)
Directory Service/CloudOnlyMicrosoftAD                 10 (API)
Directory Service/ConnectedDirectories                 10 (API)
DynamoDB/Account Max Read Capacity Units               20000 (API)
DynamoDB/Account Max Write Capacity Units              20000 (API)
DynamoDB/Global Secondary Indexes                      5
DynamoDB/Local Secondary Indexes                       5
DynamoDB/Table Max Read Capacity Units                 10000 (API)
DynamoDB/Table Max Write Capacity Units                10000 (API)
DynamoDB/Tables Per Region                             256
EBS/Active snapshots                                   10000
EBS/Active volumes                                     5000
EBS/Cold (HDD) volume storage (GiB)                    307200
EBS/General Purpose (SSD) volume storage (GiB)         102400
EBS/Magnetic volume storage (GiB)                      20480
EBS/Provisioned IOPS                                   200000
EBS/Provisioned IOPS (SSD) storage (GiB)               102400
EBS/Throughput Optimized (HDD) volume storage (GiB)    307200
EC2/Elastic IP addresses (EIPs)                        5 (API)
EC2/Max active spot fleets per region                  1000
EC2/Max launch specifications per spot fleet           50
EC2/Max spot instance requests per region              20
EC2/Max target capacity for all spot fleets in region  5000
EC2/Max target capacity per spot fleet                 3000
EC2/Rules per VPC security group                       50
EC2/Running On-Demand EC2 instances                    100 (API)
EC2/Running On-Demand c1.medium instances              20
EC2/Running On-Demand c1.xlarge instances              20
EC2/Running On-Demand c3.2xlarge instances             20
EC2/Running On-Demand c3.4xlarge instances             20
EC2/Running On-Demand c3.8xlarge instances             20
EC2/Running On-Demand c3.large instances               20
EC2/Running On-Demand c3.xlarge instances              20
EC2/Running On-Demand c4.2xlarge instances             20
EC2/Running On-Demand c4.4xlarge instances             10
EC2/Running On-Demand c4.8xlarge instances             5
EC2/Running On-Demand c4.large instances               20
EC2/Running On-Demand c4.xlarge instances              20
EC2/Running On-Demand c5.18xlarge instances            5
EC2/Running On-Demand c5.2xlarge instances             20
EC2/Running On-Demand c5.4xlarge instances             10
EC2/Running On-Demand c5.9xlarge instances             5
EC2/Running On-Demand c5.large instances               20
EC2/Running On-Demand c5.xlarge instances              20
EC2/Running On-Demand cc2.8xlarge instances            20
EC2/Running On-Demand cg1.4xlarge instances            2
EC2/Running On-Demand cr1.8xlarge instances            2
EC2/Running On-Demand d2.2xlarge instances             20
EC2/Running On-Demand d2.4xlarge instances             10
EC2/Running On-Demand d2.8xlarge instances             5
EC2/Running On-Demand d2.xlarge instances              20
EC2/Running On-Demand f1.16xlarge instances            20
EC2/Running On-Demand f1.2xlarge instances             20
EC2/Running On-Demand g2.2xlarge instances             5
EC2/Running On-Demand g2.8xlarge instances             2
EC2/Running On-Demand g3.16xlarge instances            1
EC2/Running On-Demand g3.4xlarge instances             1
EC2/Running On-Demand g3.8xlarge instances             1
EC2/Running On-Demand h1.16xlarge instances            5
EC2/Running On-Demand h1.2xlarge instances             20
EC2/Running On-Demand h1.4xlarge instances             20
EC2/Running On-Demand h1.8xlarge instances             10
EC2/Running On-Demand hi1.4xlarge instances            2
EC2/Running On-Demand hs1.8xlarge instances            2
EC2/Running On-Demand i2.2xlarge instances             8
EC2/Running On-Demand i2.4xlarge instances             4
EC2/Running On-Demand i2.8xlarge instances             2
EC2/Running On-Demand i2.xlarge instances              8
EC2/Running On-Demand i3.16xlarge instances            2
EC2/Running On-Demand i3.2xlarge instances             2
EC2/Running On-Demand i3.4xlarge instances             2
EC2/Running On-Demand i3.8xlarge instances             2
EC2/Running On-Demand i3.large instances               2
EC2/Running On-Demand i3.xlarge instances              2
EC2/Running On-Demand m1.large instances               20
EC2/Running On-Demand m1.medium instances              20
EC2/Running On-Demand m1.small instances               20
EC2/Running On-Demand m1.xlarge instances              20
EC2/Running On-Demand m2.2xlarge instances             20
EC2/Running On-Demand m2.4xlarge instances             20
EC2/Running On-Demand m2.xlarge instances              20
EC2/Running On-Demand m3.2xlarge instances             20
EC2/Running On-Demand m3.large instances               20
EC2/Running On-Demand m3.medium instances              20
EC2/Running On-Demand m3.xlarge instances              20
EC2/Running On-Demand m4.10xlarge instances            5
EC2/Running On-Demand m4.16xlarge instances            5
EC2/Running On-Demand m4.2xlarge instances             20
EC2/Running On-Demand m4.4xlarge instances             10
EC2/Running On-Demand m4.large instances               20
EC2/Running On-Demand m4.xlarge instances              20
EC2/Running On-Demand m5.12xlarge instances            5
EC2/Running On-Demand m5.24xlarge instances            5
EC2/Running On-Demand m5.2xlarge instances             20
EC2/Running On-Demand m5.4xlarge instances             10
EC2/Running On-Demand m5.large instances               20
EC2/Running On-Demand m5.xlarge instances              20
EC2/Running On-Demand p2.16xlarge instances            1
EC2/Running On-Demand p2.8xlarge instances             1
EC2/Running On-Demand p2.xlarge instances              1
EC2/Running On-Demand p3.16xlarge instances            1
EC2/Running On-Demand p3.2xlarge instances             1
EC2/Running On-Demand p3.8xlarge instances             1
EC2/Running On-Demand r3.2xlarge instances             20
EC2/Running On-Demand r3.4xlarge instances             10
EC2/Running On-Demand r3.8xlarge instances             5
EC2/Running On-Demand r3.large instances               20
EC2/Running On-Demand r3.xlarge instances              20
EC2/Running On-Demand r4.16xlarge instances            1
EC2/Running On-Demand r4.2xlarge instances             20
EC2/Running On-Demand r4.4xlarge instances             10
EC2/Running On-Demand r4.8xlarge instances             5
EC2/Running On-Demand r4.large instances               20
EC2/Running On-Demand r4.xlarge instances              20
EC2/Running On-Demand t1.micro instances               20
EC2/Running On-Demand t2.2xlarge instances             20
EC2/Running On-Demand t2.large instances               20
EC2/Running On-Demand t2.medium instances              20
EC2/Running On-Demand t2.micro instances               20
EC2/Running On-Demand t2.nano instances                20
EC2/Running On-Demand t2.small instances               20
EC2/Running On-Demand t2.xlarge instances              20
EC2/Running On-Demand x1.16xlarge instances            20
EC2/Running On-Demand x1.32xlarge instances            20
EC2/Running On-Demand x1e.32xlarge instances           20
EC2/Running On-Demand x1e.xlarge instances             20
EC2/Security groups per VPC                            500
EC2/VPC Elastic IP addresses (EIPs)                    5 (API)
EC2/VPC security groups per elastic network interface  5 (API)
ECS/Clusters                                           1000
ECS/Container Instances per Cluster                    1000
ECS/EC2 Tasks per Service (desired count)              1000
ECS/Fargate Tasks                                      20
ECS/Services per Cluster                               500
EFS/File systems                                       10
ELB/Active load balancers                              20 (API)
ELB/Listeners per application load balancer            50 (API)
ELB/Listeners per load balancer                        100 (API)
ELB/Rules per application load balancer                100 (API)
ELB/Target groups                                      3000 (API)
ElastiCache/Nodes                                      100
ElastiCache/Nodes per Cluster                          20
ElastiCache/Parameter Groups                           20
ElastiCache/Security Groups                            50
ElastiCache/Subnet Groups                              50
ElastiCache/Subnets per subnet group                   20
ElasticBeanstalk/Application versions                  1000
ElasticBeanstalk/Applications                          75
ElasticBeanstalk/Environments                          200
Firehose/Delivery streams per region                   20
IAM/Groups                                             300 (API)
IAM/Instance profiles                                  1000 (API)
IAM/Policies                                           1500 (API)
IAM/Policy Versions In Use                             10000 (API)
IAM/Roles                                              1000 (API)
IAM/Server certificates                                20 (API)
IAM/Users                                              5000 (API)
RDS/DB Cluster Parameter Groups                        50 (API)
RDS/DB Clusters                                        40 (API)
RDS/DB instances                                       40 (API)
RDS/DB parameter groups                                50 (API)
RDS/DB security groups                                 25 (API)
RDS/DB snapshots per user                              100 (API)
RDS/Event Subscriptions                                20 (API)
RDS/Max auths per security group                       20 (API)
RDS/Option Groups                                      20 (API)
RDS/Read replicas per master                           5 (API)
RDS/Reserved Instances                                 40 (API)
RDS/Storage quota (GB)                                 100000 (API)
RDS/Subnet Groups                                      50 (API)
RDS/Subnets per Subnet Group                           20 (API)
RDS/VPC Security Groups                                5
Redshift/Redshift manual snapshots                     20
Redshift/Redshift subnet groups                        20
S3/Buckets                                             100
SES/Daily sending quota                                200
VPC/Entries per route table                            50
VPC/Internet gateways                                  5
VPC/NAT Gateways per AZ                                5
VPC/Network ACLs per VPC                               200
VPC/Route tables per VPC                               200
VPC/Rules per network ACL                              20
VPC/Subnets per VPC                                    200
VPC/VPCs                                               5
VPC/Virtual private gateways                           5

**Expected Output**
Talking about ec2 instance types and its available amount, here is the information what I have on my account, and what I expect to see from the awslimitchecker:

Running On-Demand c1.medium instances 100
Running On-Demand c1.xlarge instances 100
Running On-Demand c3.2xlarge instances 100
Running On-Demand c3.4xlarge instances 100
Running On-Demand c3.8xlarge instances 100
Running On-Demand c3.large instances 100
Running On-Demand c3.xlarge instances 100
Running On-Demand c4.2xlarge instances 100
Running On-Demand c4.4xlarge instances 100
Running On-Demand c4.8xlarge instances 100
Running On-Demand c4.large instances 100
Running On-Demand c4.xlarge instances 100
Running On-Demand c5.18xlarge instances 5
Running On-Demand c5.2xlarge instances 20
Running On-Demand c5.4xlarge instances 10
Running On-Demand c5.9xlarge instances 5
Running On-Demand c5.large instances 20
Running On-Demand c5.xlarge instances 20
Running On-Demand d2.2xlarge instances 8
Running On-Demand d2.4xlarge instances 4
Running On-Demand d2.8xlarge instances 2
Running On-Demand d2.xlarge instances 8
Running On-Demand g2.2xlarge instances 5
Running On-Demand g2.8xlarge instances 2
Running On-Demand g3.16xlarge instances 0
Running On-Demand g3.4xlarge instances 1
Running On-Demand g3.8xlarge instances 1
Running On-Demand i2.2xlarge instances 8
Running On-Demand i2.4xlarge instances 4
Running On-Demand i2.8xlarge instances 2
Running On-Demand i2.xlarge instances 8
Running On-Demand i3.16xlarge instances 1
Running On-Demand i3.2xlarge instances 4
Running On-Demand i3.4xlarge instances 2
Running On-Demand i3.8xlarge instances 2
Running On-Demand i3.large instances 16
Running On-Demand i3.xlarge instances 6
Running On-Demand m1.large instances 100
Running On-Demand m1.medium instances 100
Running On-Demand m1.small instances 100
Running On-Demand m1.xlarge instances 100
Running On-Demand m2.2xlarge instances 100
Running On-Demand m2.4xlarge instances 100
Running On-Demand m2.xlarge instances 100
Running On-Demand m3.2xlarge instances 100
Running On-Demand m3.large instances 100
Running On-Demand m3.medium instances 100
Running On-Demand m3.xlarge instances 100
Running On-Demand m4.10xlarge instances 5
Running On-Demand m4.16xlarge instances 5
Running On-Demand m4.2xlarge instances 100
Running On-Demand m4.4xlarge instances 10
Running On-Demand m4.large instances 20
Running On-Demand m4.xlarge instances 40
Running On-Demand m5.12xlarge instances 3
Running On-Demand m5.24xlarge instances 2
Running On-Demand m5.2xlarge instances 20
Running On-Demand m5.4xlarge instances 10
Running On-Demand m5.large instances 20
Running On-Demand m5.xlarge instances 20
Running On-Demand r3.2xlarge instances 20
Running On-Demand r3.4xlarge instances 10
Running On-Demand r3.8xlarge instances 5
Running On-Demand r3.large instances 20
Running On-Demand r3.xlarge instances 20
Running On-Demand r4.16xlarge instances 1
Running On-Demand r4.2xlarge instances 20
Running On-Demand r4.4xlarge instances 10
Running On-Demand r4.8xlarge instances 5
Running On-Demand r4.large instances 20
Running On-Demand r4.xlarge instances 20
Running On-Demand t1.micro instances 100
Running On-Demand t2.2xlarge instances 20
Running On-Demand t2.large instances 100
Running On-Demand t2.medium instances 100
Running On-Demand t2.micro instances 100
Running On-Demand t2.nano instances 100
Running On-Demand t2.small instances 100
Running On-Demand t2.xlarge instances 20

**Testing Assistance**
Yes

**Comment by jantman** [comment]
Michael,

I think I was confused by your first post. The response above is running with ``-l`` for showing the limits, not the actual usage.

Since your account doesn't have TrustedAdvisor, YOU need to tell awslimitchecker what the Running On-Demand EC2 limits are; AWS does not provide a way to retrieve this programmatically.

See e.g. [Supported Limits - EC2](http://awslimitchecker.readthedocs.io/en/latest/limits.html#ec2) which lists which limits are available via TrustedAdvisor (TA) or the API. Any limit that isn't available via TA or API will just use the published default limit unless you manually override it. You can override a limit either when using awslimitchecker [via the command line](http://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#overriding-limits) or when using it [from Python](http://awslimitchecker.readthedocs.io/en/latest/python_usage.html#setting-a-limit-override).

**Comment by Michael1001** [comment]
Jantman, 
thank you for your answer.
I understand it well, if my account will not have AWS Premium Support Subscription, in this case, this tool could not give real information, about available limits for all the ec2 instance types?

**Comment by jantman** [comment]
Michael,

Without Premium Support, the tool gives real information about your current **usage**. You need to tell it what your limits are.

If you have a normal/basic account, you can for example tell awslimitchecker that your "Running On-Demand t2.micro" limit is 1000 and it will alert you when you reach a specified percentage of that.

But for any limit that doesn't have an API to retrieve it, you need to manually specify what your limit is if you've received a limit increase from AWS Support.

This is still the case for many accounts even with premium support.

**Comment by jantman** [comment]
To clarify: the real purpose of awslimitchecker isn't to tell you what your limits are, it's to alert you when your actual usage approaches your limits.

**Comment by Michael1001** [comment]
Jantman, thank you so much, for you explanations. Now I understand where was the problem.

**Comment by jantman** [comment]
Sure, glad to clarify! If you have any more issues, feel free to open another ticket!

Best of luck
Jason
