### ISSUE TITLE
Uncaught error when checking SES limit for non-supported region

### ISSUE THREAD

**Issue by bergkampsliew** [jantman/awslimitchecker#375]
- When running command "aws ses get-send-quota" against non-supported SES regions, we normally get error message such as _Could not connect to the endpoint URL: "https://email.eu-west-2.amazonaws.com/_
- However, I noticed that since 8 Jan 2019, the command has returned different error message for non-supported region such as eu-central-1.
_"botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetSendQuota operation: Unknown"_
- After checking with AWS Support, it is due to Pinpoint service being rolled out to eu-central-1 which uses the endpoint hence different error response.
https://aws.amazon.com/about-aws/whats-new/2019/01/amazon-pinpoint-is-now-available-in-three-additional-regions/ 

Since awslimitchecker is using that API call for SES check (https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/services/ses.py#L105), the mentioned exception is not supported or handled as described above. Hence, the check will result as error with botocore stacktrace as the output.

The expected output would be that awslimitchecker gracefully handle the exception and only print short message together with the returned reason from AWS API , without stacktrace.

**Comment by jantman** [comment]
@bergkampsliew please fill in the full template that's provided when opening a new issue. Specifically, please provide:

### Version

awslimitchecker version, as reported by ``awslimitchecker --version``

### Installation Method

How was awslimitchecker installed (provide as much detail as possible, ideally
the exact command used and whether it was installed in a virtualenv or not).

### Supporting Software Versions

The output of ``python --version`` and ``virtualenv --version`` in the environment
that awslimitchecker is running in, as well as your operating system type and version.

### Actual Output

```
Paste here the output of awslimitchecker (including the command used to run it),
run with the -vv (debug-level output) flag, that shows the issue.
```

### Expected Output

Describe the output that you expected (what's wrong). If possible, after your description,
copy the actual output above and modify it to what was expected.

### TrustedAdvisor

If the bug/issue is related to TrustedAdvisor, which support contract your account has.

### Testing Assistance

Indicate whether or not you will be able to assist in testing pre-release
code for the feature.

**Comment by bergkampsliew** [comment]
So sorry, I knew I was forgetting something when filling out the issue description.

### Version

5.1.0
(and reproducible using develop branch)

### Installation Method

pip, without virtualenv

### Supporting Software Versions

python 2.7.9
(and also python 3.5.3 when testing with develop branch)

### Actual Output

when running command **awslimitchecker --region eu-central-1**, then compare it against result from another region using command **awslimitchecker --region ap-northeast-1**

below exception wasn't handled and stacktrace output by command using eu-central-1, while command with ap-northeast-1 does not produce any and exception was handled.
```
Traceback (most recent call last):
File "/usr/local/bin/awslimitchecker", line 11, in
sys.exit(console_entry_point())
File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/runner.py", line 415, in console_entry_point
r.console_entry_point()
File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/runner.py", line 409, in console_entry_point
res = self.check_thresholds()
File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/runner.py", line 310, in check_thresholds
service=self.service_name)
File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/checker.py", line 553, in check_thresholds
cls._update_limits_from_api()
File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/services/ses.py", line 105, in _update_limits_from_api
resp = self.conn.get_send_quota()
File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetSendQuota operation: Unknown
```

### Expected Output

awslimitchecker gracefully handle the exception and only print short message together with the returned reason from AWS API , without stacktrace.

### TrustedAdvisor

-

### Testing Assistance

made a PR and tested locally

**Comment by jantman** [comment]
This has been released in [6.0.1](https://github.com/jantman/awslimitchecker/releases/tag/6.0.1) which is now live [on PyPI](https://pypi.org/project/awslimitchecker/). Thank you so much @bergkampsliew !!
