### ISSUE TITLE
Timeout on ds.eu-west-3.amazonaws.com - Directory Services

### ISSUE THREAD

**Issue by wolruf** [jantman/awslimitchecker#403]
## Bug Report

Using eu-west-3 times out, when eu-west-1 has no issues.

### Version

6.1.5

### Installation Method

pip install awslimitchecker
didn't use virtualenv

### Supporting Software Versions

Python 2.7.10
not using virtualenv
macOS 10.4.4

### Actual Output

```
➜  Downloads awslimitchecker -r eu-west-3 -vv               
awslimitchecker None is AGPL-licensed free software; all users have a right to the full source code of this version. See <None>
2019-04-14 10:03:06,957 [DEBUG checker.py:213 - awslimitchecker.checker._boto_conn_kwargs() ] Connecting to region eu-west-3
2019-04-14 10:03:06,958 [DEBUG cloudtrail.py:116 - awslimitchecker.services.cloudtrail.get_limits() ] Gathering CloudTrail's limits from AWS
2019-04-14 10:03:07,051 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to dynamodb in region eu-west-3
2019-04-14 10:03:07,052 [DEBUG lambdafunc.py:82 - awslimitchecker.services.lambdafunc.get_limits() ] Getting limits for Lambda
2019-04-14 10:03:07,053 [DEBUG cloudtrail.py:116 - awslimitchecker.services.cloudtrail.get_limits() ] Gathering CloudTrail's limits from AWS
2019-04-14 10:03:07,053 [DEBUG lambdafunc.py:82 - awslimitchecker.services.lambdafunc.get_limits() ] Getting limits for Lambda
2019-04-14 10:03:07,066 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to support in region us-east-1
2019-04-14 10:03:07,067 [INFO trustedadvisor.py:162 - awslimitchecker.trustedadvisor._poll() ] Beginning TrustedAdvisor poll
2019-04-14 10:03:07,067 [DEBUG trustedadvisor.py:219 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Querying Trusted Advisor checks
2019-04-14 10:03:07,069 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:03:07,069 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (1): support.us-east-1.amazonaws.com
2019-04-14 10:03:07,527 [DEBUG connectionpool.py:396 - urllib3.connectionpool._make_request() ] https://support.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 400 120
2019-04-14 10:03:07,529 [WARNING trustedadvisor.py:228 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
2019-04-14 10:03:07,530 [INFO trustedadvisor.py:165 - awslimitchecker.trustedadvisor._poll() ] TrustedAdvisor.have_ta is False; not polling TA
2019-04-14 10:03:07,530 [DEBUG trustedadvisor.py:402 - awslimitchecker.trustedadvisor._update_services() ] Updating TA limits on all services
2019-04-14 10:03:07,530 [INFO trustedadvisor.py:422 - awslimitchecker.trustedadvisor._update_services() ] Done updating TA limits on all services
2019-04-14 10:03:07,530 [DEBUG cloudtrail.py:61 - awslimitchecker.services.cloudtrail.find_usage() ] Checking usage for service CloudTrail
2019-04-14 10:03:07,543 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to cloudtrail in region eu-west-3
2019-04-14 10:03:07,546 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:03:07,546 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (1): cloudtrail.eu-west-3.amazonaws.com
2019-04-14 10:03:07,768 [DEBUG connectionpool.py:396 - urllib3.connectionpool._make_request() ] https://cloudtrail.eu-west-3.amazonaws.com:443 "POST / HTTP/1.1" 200 686
2019-04-14 10:03:07,771 [DEBUG cloudtrail.py:101 - awslimitchecker.services.cloudtrail._find_usage_cloudtrail() ] Ignoring event selectors and data resources for CloudTrail xxx-DO-NOT-DELETE in non-home region
2019-04-14 10:03:07,771 [DEBUG cloudtrail.py:101 - awslimitchecker.services.cloudtrail._find_usage_cloudtrail() ] Ignoring event selectors and data resources for CloudTrail blop in non-home region
2019-04-14 10:03:07,771 [DEBUG cloudtrail.py:69 - awslimitchecker.services.cloudtrail.find_usage() ] Done checking usage.
2019-04-14 10:03:07,771 [DEBUG s3.py:60 - awslimitchecker.services.s3.find_usage() ] Checking usage for service S3
2019-04-14 10:03:07,888 [INFO connectable.py:108 - awslimitchecker.connectable.connect_resource() ] Connected to s3 (resource) in region eu-west-3
2019-04-14 10:03:07,906 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:03:07,906 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (1): s3.eu-west-3.amazonaws.com
2019-04-14 10:03:08,112 [DEBUG connectionpool.py:396 - urllib3.connectionpool._make_request() ] https://s3.eu-west-3.amazonaws.com:443 "GET / HTTP/1.1" 200 None
2019-04-14 10:03:08,119 [DEBUG s3.py:71 - awslimitchecker.services.s3.find_usage() ] Done checking usage.
2019-04-14 10:03:08,119 [DEBUG directoryservice.py:125 - awslimitchecker.services.directoryservice._update_limits_from_api() ] Setting DirectoryService limits from API
2019-04-14 10:03:08,145 [INFO connectable.py:90 - awslimitchecker.connectable.connect() ] Connected to ds in region eu-west-3
2019-04-14 10:03:08,148 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:03:08,148 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (1): ds.eu-west-3.amazonaws.com
2019-04-14 10:04:08,581 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:04:08,582 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (2): ds.eu-west-3.amazonaws.com
2019-04-14 10:05:09,780 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:05:09,780 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (3): ds.eu-west-3.amazonaws.com
2019-04-14 10:06:12,300 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:06:12,300 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (4): ds.eu-west-3.amazonaws.com
2019-04-14 10:07:17,662 [DEBUG retry.py:200 - urllib3.util.retry.from_int() ] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-14 10:07:17,662 [DEBUG connectionpool.py:824 - urllib3.connectionpool._new_conn() ] Starting new HTTPS connection (5): ds.eu-west-3.amazonaws.com
Traceback (most recent call last):
  File "/Users/ocahagne/Library/Python/2.7/bin/awslimitchecker", line 10, in <module>
    sys.exit(console_entry_point())
  File "/Users/ocahagne/Library/Python/2.7/lib/python/site-packages/awslimitchecker/runner.py", line 415, in console_entry_point
    r.console_entry_point()
  File "/Users/ocahagne/Library/Python/2.7/lib/python/site-packages/awslimitchecker/runner.py", line 409, in console_entry_point
    res = self.check_thresholds()
  File "/Users/ocahagne/Library/Python/2.7/lib/python/site-packages/awslimitchecker/runner.py", line 310, in check_thresholds
    service=self.service_name)
  File "/Users/ocahagne/Library/Python/2.7/lib/python/site-packages/awslimitchecker/checker.py", line 553, in check_thresholds
    cls._update_limits_from_api()
  File "/Users/ocahagne/Library/Python/2.7/lib/python/site-packages/awslimitchecker/services/directoryservice.py", line 127, in _update_limits_from_api
    resp = self.conn.get_directory_limits()
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 611, in _make_api_call
    operation_model, request_dict)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 136, in _send_request
    success_response, exception):
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 210, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "https://ds.eu-west-3.amazonaws.com/"
```

### Expected Output

Not timing out with CDG region.

### Testing Assistance

Yes, willing to test pre-release code.

**Comment by jantman** [comment]
@wolruf Apologies for taking a bit to reply to this.

According to the [AWS regions documentation](https://docs.aws.amazon.com/general/latest/gr/rande.html#ds_region), DS is not a valid service in the eu-west-3 region at this time - in eu-west, 1 and 2 have DS but not 3. That would explain the exact error you're seeing.

**Comment by wolruf** [comment]
Thanks @jantman I'll skip the service for the moment.
