### ISSUE TITLE
Error running docker for the first time, Invalid endpoint

### ISSUE THREAD

**Issue by fatoh2** [jantman/awslimitchecker#565]
## Bug Report

When reporting a bug in awslimitchecker, please provide all of the following information,
as well as any additional details that may be useful in reproducing or fixing
the issue:

### Version

awslimitchecker 12.0.0

### Installation Method

Running using docker with local credentials file, as stated here:
https://awslimitchecker.readthedocs.io/en/latest/docker.html

### Supporting Software Versions

macOS 11.2.3

### Actual Output

```
docker run \
    -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
    awslimitchecker --version
awslimitchecker 12.0.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
Traceback (most recent call last):
  File "/usr/local/bin/awslimitchecker", line 33, in <module>
    sys.exit(load_entry_point('awslimitchecker', 'console_scripts', 'awslimitchecker')())
  File "/awslimitchecker/awslimitchecker/runner.py", line 550, in console_entry_point
    r.console_entry_point()
  File "/awslimitchecker/awslimitchecker/runner.py", line 432, in console_entry_point
    self.checker = AwsLimitChecker(
  File "/awslimitchecker/awslimitchecker/checker.py", line 194, in __init__
    self.services[sname] = cls(warning_threshold,
  File "/awslimitchecker/awslimitchecker/services/base.py", line 93, in __init__
    self.limits = self.get_limits()
  File "/awslimitchecker/awslimitchecker/services/dynamodb.py", line 145, in get_limits
    self.connect()
  File "/awslimitchecker/awslimitchecker/connectable.py", line 122, in connect
    self.conn = boto3.client(self.api_name, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 270, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 841, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 91, in create_client
    client_args = self._get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 360, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 99, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 286, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://dynamodb..amazonaws.com
```

### Expected Output

Failing with the error "Invalid endpoint: https://dynamodb..amazonaws.com", not sure why there are two dots there.

**Comment by jantman** [comment]
You need to set ``AWS_DEFAULT_REGION``. The two dots are there because the region name should be between them, but it's empty/unset.
