### ISSUE TITLE
ElastiCache CacheCluster CacheNodes can be None

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#65]
Check for this and catch it (using 0.1.2 from pypi):

```
18:00:45 Checking AWS resource usage; WARNING threshold 80% of limit, CRITICAL threshold 99% of limit
18:00:45 Traceback (most recent call last):
18:00:45   File "/var/lib/jenkins/workspace/AWS_Limit_Check/cmVE/bin/cm", line 5, in <module>
18:00:45     run()
18:00:45   File "/var/lib/jenkins/workspace/AWS_Limit_Check/cmVE/lib/python2.6/site-packages/cm/__init__.py", line 80, in run
18:00:45     cmd.run()
18:00:45   File "/var/lib/jenkins/workspace/AWS_Limit_Check/cmVE/lib/python2.6/site-packages/cm/commands/check_aws_limits.py", line 53, in run
18:00:45     result = checker.check_thresholds()
18:00:45   File "/var/lib/jenkins/workspace/AWS_Limit_Check/cmVE/lib/python2.6/site-packages/awslimitchecker/checker.py", line 368, in check_thresholds
18:00:45     tmp = cls.check_thresholds()
18:00:45   File "/var/lib/jenkins/workspace/AWS_Limit_Check/cmVE/lib/python2.6/site-packages/awslimitchecker/services/base.py", line 240, in check_thresholds
18:00:45     self.find_usage()
18:00:45   File "/var/lib/jenkins/workspace/AWS_Limit_Check/cmVE/lib/python2.6/site-packages/awslimitchecker/services/elasticache.py", line 71, in find_usage
18:00:45     self._find_usage_nodes()
18:00:45   File "/var/lib/jenkins/workspace/AWS_Limit_Check/cmVE/lib/python2.6/site-packages/awslimitchecker/services/elasticache.py", line 85, in _find_usage_nodes
18:00:45     nodes += len(cluster['CacheNodes'])
18:00:45 TypeError: object of type 'NoneType' has no len()
```

Bug is here: https://github.com/jantman/awslimitchecker/blob/ae379712244f512b154a9e237567243613a8432f/awslimitchecker/services/elasticache.py#L85

**Comment by sstarcher** [comment]
Using off master I got the same issue

```
  File "/usr/local/lib/python2.7/site-packages/awslimitchecker/checker.py", line 329, in find_usage
    cls.find_usage()
  File "/usr/local/lib/python2.7/site-packages/awslimitchecker/services/elasticache.py", line 65, in find_usage
    self._find_usage_nodes()
  File "/usr/local/lib/python2.7/site-packages/awslimitchecker/services/elasticache.py", line 81, in _find_usage_nodes
    num_nodes = len(cluster['CacheNodes'])
KeyError: 'CacheNodes'
```

**Comment by jantman** [comment]
@sstarcher that's a subtly different bug, but the same end result. I've opened #257 for it.
